name: Auto-Release (by PSModule)
description: Automatically creates releases based on pull requests and labels.
author: PSModule
branding:
  icon: activity
  color: blue

inputs:
  AutoCleanup:
    description: Control wether to automatically delete the prerelease tags after the stable release is created.
    required: false
    default: 'true'
  AutoPatching:
    description: Control wether to automatically handle patches. If disabled, the action will only create a patch release if the pull request has a 'patch' label.
    required: false
    default: 'true'
  ConfigurationFile:
    description: The path to the configuration file. Settings in the configuration file take precedence over the action inputs.
    required: false
    default: .github\auto-release.yml
  CreateMajorTag:
    description: Control wether to create a major tag when a pull request is merged into the main branch.
    required: false
    default: 'true'
  CreateMinorTag:
    description: Control wether to create a minor tag when a pull request is merged into the main branch.
    required: false
    default: 'true'
  DatePrereleaseFormat:
    description: If specified, uses a date based prerelease scheme. The format should be a valid .NET format string like 'yyyyMMddHHmm'.
    required: false
    default: ''
  IgnoreLabels:
    description: A comma separated list of labels that do not trigger a release.
    required: false
    default: NoRelease
  IncrementalPrerelease:
    description: Control wether to automatically increment the prerelease number. If disabled, the action will ensure only one prerelease exists for a given branch.
    required: false
    default: 'true'
  MajorLabels:
    description: A comma separated list of labels that trigger a major release.
    required: false
    default: major, breaking
  MinorLabels:
    description: A comma separated list of labels that trigger a minor release.
    required: false
    default: minor, feature, improvement
  PatchLabels:
    description: A comma separated list of labels that trigger a patch release.
    required: false
    default: patch, fix, bug
  VersionPrefix:
    description: The prefix to use for the version number.
    required: false
    default: v
  WhatIf:
    description: If specified, the action will only log the changes it would make, but will not actually create or delete any releases or tags.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Auto-Release
      shell: pwsh
      env:
        AutoCleanup: ${{ inputs.AutoCleanup }}
        AutoPatching: ${{ inputs.AutoPatching }}
        ConfigurationFile: ${{ inputs.ConfigurationFile }}
        CreateMajorTag: ${{ inputs.CreateMajorTag }}
        CreateMinorTag: ${{ inputs.CreateMinorTag }}
        DatePrereleaseFormat: ${{ inputs.DatePrereleaseFormat }}
        IgnoreLabels: ${{ inputs.IgnoreLabels }}
        IncrementalPrerelease: ${{ inputs.IncrementalPrerelease }}
        MajorLabels: ${{ inputs.MajorLabels }}
        MinorLabels: ${{ inputs.MinorLabels }}
        PatchLabels: ${{ inputs.PatchLabels }}
        VersionPrefix: ${{ inputs.VersionPrefix }}
        WhatIf: ${{ inputs.WhatIf }}
      run: . "$env:GITHUB_ACTION_PATH\scripts\main.ps1"
